#pragma config(Motor,  port2,           Left,          tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port9,           Right,         tmotorServoContinuousRotation, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//Global variables
float joystickAxis[7] = {0,0,0,0,0,0,0};
float smoothJoystickAxis[7] = {0,0,0,0,0,0,0};
long lastAccelTime = nSysTime;
float left_speed;
float right_speed;
int lowSpeed = 0;
bool tank = true;
bool arcade = false;
float power = 2;
float kAccelVal = 1;
int deadBand = 10;

/////////////////////////////////////////////////////////////////////////////////////////
//
//                         Driver Skills Template
//
// This is a template for the driver skills competition. It is identical in structure to
// the standard competition template except that the two "#pragma' statements above (and
// copied below) adjust the time limits for the competition.
//				#pragma autonomousDuration(0)
//				#pragma userControlDuration(60)
// The autonomous duration for "Driver Skills" is zero; i.e. there is no autonomous phase.
// The user control duration is 60 seconds
//
// NOTE: The above two pragmas only impact the Crystal implementation. For systems using
//       VEXNET, the VEXNET system ignores these statements as it has the durations
//       for the competition built-in.
//
// Whenever this user program is run, the duration is automatically sent to the VEX master
// processor. The master CPU will only accept these commands once per power=on cycle. So, it's
// best to power cycle your VEX to ensure that they get recognized in case you were
// previously running a standard competition program with different durations.
//
// Testing Via Crystals:
// ====================
//
// The procedure to test a Driver Skills program using the crystals is as follows:
//
// 1. Turn off power to the Crystal transmitter/joysticks.
//
// 2. Turn on your VEX so that the Driver Skills program is running.
//
// 3. Driver skills program segment of your program will start running. At the end of 60
//    seconds the VEX Master CPU will turn off the motors.
//
// 4. Repeat the above sequence
//
//
// Testing Via VEXNET Using VEXNET Competition Switch
// ==================================================
//
// The procedure to test a Driver Skills program using VEXNET Competition Switch is as follows:
//
// 1. Set the two switches on the Competition switch to "DISABLE" and "USER CONTROL"
//
// 2. Start the Driver skills program
//
// 3. Set Switch to ENABLE from DISABLE
//
// 4. You need to manually time the 60 second duration.
//
// 5. Set Switch to DISABLE
//
// 6. Repeat from step (3) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
//
// Testing Via VEXNET Using ROBOTC IDE
// ==================================================
//
// It is not necessary to own a VEXNET switch. ROBOTC has a test window that allows the same functionality.
// The test window has three buttons for "DISABLE", "AUTONOMOUS", "USER CONTROL".
//
// 1. Open the ROBOTC Debugger. Then open the "Competition Control" Debugger window.
//
// 2. Start your Driver Skills program running.
//
// 3. Click the "DISABLED" button on the "Competition Control" window.
//
// 4. Click the "USER CONTROL" button on the "Competition Control" window.
//
// 5. You need to manually time the 60 second duration.
//
// 6. Click the "DISABLED" button on the "Competition Control" window.
//
// 7. Repeat from step (4) to run subsequent test runs. There's no need to reset the VEX or
//    restart your user program.
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// The "Driver Skills" competition has no autonomous phase. Simply leave the following
// placeholder.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

void Sense()
{
	joystickAxis[1] = vexRT[Ch1];
	joystickAxis[2] = vexRT[Ch2];
	joystickAxis[3] = vexRT[Ch3];
	joystickAxis[4] = vexRT[Ch4];
	joystickAxis[5] = vexRT[Ch5];
	joystickAxis[6] = vexRT[Ch6];

	if (vexRT[Btn8U] == 1){
		lowSpeed = 1;
	}
	else if (vexRT[Btn8D] == 0) {
		lowSpeed = 0;
	}

	if (vexRT[Btn8R] == 1) {
		tank = false;
		arcade = true;
	}
	else if (vexRT[Btn8L] == 1) {
		tank = true;
		arcade = false;
	}
}

void Accelerate()
{
	if(nSysTime-lastAccelTime>50 || lastAccelTime-nSysTime>50000) 
	{
		float tempVal;
		lastAccelTime=nSysTime;
		for(int i=1; i<=6; i++)
		{
			if(joystickAxis[i] > deadBand && joystickAxis[i] < -deadBand)
			{
				joystickAxis[i] = 0;
			}
			if(joystickAxis[i]>=0) {
				tempVal = pow(joystickAxis[i],power);
			}
			else {
				tempVal = -pow(-joystickAxis[i],power);
			}
			if (abs(tempVal - smoothJoystickAxis[i]) > kAccelVal) {
				//bring the motor value closer to the joystick by 1%
			smoothJoystickAxis[i] =+ (tempVal > smoothJoystickAxis[i]) ? kAccelVal : -1*kAccelVal;
			}
		}
	}
}

void DoWork()
{
	//66% NORMAL SPEED
	if (lowSpeed == 0) {
		left_speed = smoothJoystickAxis[3]*0.66;
		right_speed = smoothJoystickAxis[2]*0.66;
	}

	//33% BUMP SPEED
	else if (lowSpeed == 1) {
		left_speed = smoothJoystickAxis[3]*0.33;
		right_speed = smoothJoystickAxis[3]*0.33;
	}

	//Tank Drive
	if(tank) {
		motor[Left] = left_speed;
		motor[Right] = right_speed;
	}

	//Arcade drive
	if(arcade) {
		motor[Left] = (smoothJoystickAxis[2] + smoothJoystickAxis[3]);
		motor[Right] = (smoothJoystickAxis[2] - smoothJoystickAxis[3]);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop
	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		Sense();
		Accelerate();
		DoWork();
	}
}
